// Verifying a Premium payment and activating access.
//
// The one rule this file exists to enforce: Premium is only ever activated after a
// server-to-server validation call to SSLCommerz confirms the money was taken, for
// the right amount, against a transaction we created. Nothing in the browser's
// redirect or the callback POST body is trusted on its own.

import Elder from "@/models/Elder";
import SubscriptionPayment from "@/models/SubscriptionPayment";
import { validateTransaction, queryTransaction } from "@/lib/sslcommerz";
import { extendPeriod } from "@/lib/subscription";

/**
 * Validates a transaction with the gateway and, if it is genuinely paid, activates
 * Premium on the elder.
 *
 * Safe to call more than once for the same transaction: SSLCommerz sends both a
 * success callback and an IPN, and they can arrive in either order or twice. A
 * payment already marked `paid` short-circuits, so the subscription period is never
 * extended twice for one payment.
 *
 * @returns {{ outcome: string, payment?: object, elder?: object, reason?: string }}
 *          outcome is "activated" | "already-active" | "rejected" | "unknown-transaction"
 */
export async function verifyAndActivate({ tranId, valId }) {
  if (!tranId) return { outcome: "unknown-transaction", reason: "No transaction id supplied" };

  const payment = await SubscriptionPayment.findOne({ tranId });
  if (!payment) {
    // The transaction id is generated by us and unguessable, so this means a forged
    // or stale callback. Nothing is created in response.
    return { outcome: "unknown-transaction", reason: "No matching payment record" };
  }

  if (payment.status === "paid") {
    return { outcome: "already-active", payment };
  }

  // With a val_id (normal callback) use the validation API. Without one — the
  // reconcile path, when no callback ever arrived — ask the gateway about our
  // tran_id directly. Both return the same normalised shape and both are
  // server-to-server calls authenticated with the store credentials.
  const validation = valId
    ? await validateTransaction(valId)
    : await queryTransaction(payment.tranId);

  // Every one of these must hold before a single taka of access is granted.
  const problems = [];
  if (!validation.valid) problems.push(`gateway status ${validation.status}`);
  if (validation.tranId && validation.tranId !== payment.tranId) {
    problems.push(`transaction id mismatch (${validation.tranId})`);
  }
  // Amount is compared against what we recorded when the session was created, not
  // against anything supplied in the callback, so a tampered amount cannot buy
  // Premium cheaply.
  if (Math.round(validation.amount) < Math.round(payment.amount)) {
    problems.push(`paid ${validation.amount} but expected ${payment.amount}`);
  }
  if (validation.currency && validation.currency !== payment.currency) {
    problems.push(`currency ${validation.currency}`);
  }

  if (problems.length) {
    payment.status = "failed";
    payment.failureReason = `Validation failed: ${problems.join("; ")}`;
    payment.gatewayResponse = validation.raw ?? {};
    await payment.save();
    return { outcome: "rejected", payment, reason: payment.failureReason };
  }

  const elder = await Elder.findById(payment.elderId);
  if (!elder) {
    payment.status = "failed";
    payment.failureReason = "Elder no longer exists";
    await payment.save();
    return { outcome: "rejected", payment, reason: payment.failureReason };
  }

  const now = new Date();
  const { periodStart, periodEnd } = extendPeriod(elder, payment.months, now);

  elder.subscription = {
    plan: "premium",
    status: "active",
    currentPeriodEnd: periodEnd,
    activatedAt: elder.subscription?.activatedAt ?? now,
    lastPaymentId: payment._id
  };
  await elder.save();

  payment.status = "paid";
  payment.valId = valId || validation.valId || "";
  payment.cardType = validation.cardType;
  payment.bankTranId = validation.bankTranId;
  payment.periodStart = periodStart;
  payment.periodEnd = periodEnd;
  payment.paidAt = now;
  payment.gatewayResponse = validation.raw ?? {};
  await payment.save();

  return { outcome: "activated", payment, elder };
}

/** Records a failed or cancelled attempt. Never touches the elder's access. */
export async function markUnsuccessful({ tranId, status, reason, raw }) {
  if (!tranId) return null;
  const payment = await SubscriptionPayment.findOne({ tranId });
  if (!payment) return null;

  // A callback arriving after the payment already succeeded (out-of-order IPN) must
  // not revoke access that was correctly granted.
  if (payment.status === "paid") return payment;

  payment.status = status;
  payment.failureReason = reason || "";
  payment.gatewayResponse = raw ?? {};
  await payment.save();
  return payment;
}
