// A curated list of medical conditions commonly relevant to elder wellbeing
// monitoring, used to power the disease search bar on the Register Elder
// form. This is not an exhaustive global disease registry (that would need a
// real medical terminology API like ICD-11 or SNOMED CT) — it's a practical
// set covering the conditions most likely to come up for this use case, and
// anything not on the list can still be entered via "Other".
const MEDICAL_CONDITIONS = [
  "Alzheimer's Disease",
  "Anemia",
  "Angina",
  "Anxiety Disorder",
  "Arthritis",
  "Asthma",
  "Atrial Fibrillation",
  "Benign Prostatic Hyperplasia (BPH)",
  "Bronchitis",
  "Cataracts",
  "Chronic Back Pain",
  "Chronic Fatigue Syndrome",
  "Chronic Kidney Disease",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Congestive Heart Failure",
  "Constipation (Chronic)",
  "Coronary Artery Disease",
  "Deep Vein Thrombosis",
  "Dementia",
  "Depression",
  "Diabetes Type 1",
  "Diabetes Type 2",
  "Diabetic Neuropathy",
  "Diabetic Retinopathy",
  "Epilepsy",
  "Fibromyalgia",
  "GERD (Acid Reflux)",
  "Glaucoma",
  "Gout",
  "Hearing Loss",
  "Heart Disease",
  "Hepatitis",
  "Hernia",
  "High Cholesterol",
  "Hypertension",
  "Hyperthyroidism",
  "Hypothyroidism",
  "Insomnia",
  "Kidney Stones",
  "Liver Disease",
  "Lupus",
  "Macular Degeneration",
  "Malnutrition",
  "Migraine",
  "Multiple Sclerosis",
  "Obesity",
  "Osteoarthritis",
  "Osteoporosis",
  "Parkinson's Disease",
  "Peptic Ulcer",
  "Peripheral Neuropathy",
  "Pneumonia",
  "Prostate Enlargement",
  "Rheumatoid Arthritis",
  "Sciatica",
  "Skin Condition - Eczema",
  "Skin Condition - Psoriasis",
  "Sleep Apnea",
  "Stroke (History of)",
  "Tuberculosis",
  "Urinary Incontinence",
  "Varicose Veins",
  "Vertigo",
];

export default MEDICAL_CONDITIONS;